### ISSUE TITLE
`playlist` with #:transitions broken

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#25]
```racket
(swiping-playlist (color "green") (clip vid-mp4))
(define swiping-playlist
  (λ (a b)
    (playlist a b
              #:transitions
              (list
               (composite-transition 0 0 1/2 1/2
                                     #:top a
                                     #:bottom b)))))
```

produces 
```
field-element-track: contract violation
  expected: field-element?
  given: #<procedure:transition>
  context...:
   /home/stchang/racket/racket-video/base.rkt:146:0
```
